#load("@EmbeddedSystemsBuildScripts//Unity:unity.bzl", "mock", "unity_test")
#
#unity_test(
#    file_name = "PeripheralInterface_Test.c",
#    deps = [
#        ":MockMutex",
#        "//:PeripheralInterface",
#    ],
#)
#
#unity_test(
#    file_name = "PeripheralSPIImpl_Test.c",
#    deps = [
#        ":MockMutex",
#        "//:PeripheralInterface",
#    ],
#)
#
#unity_test(
#    file_name = "Usart_Test.c",
#    deps = [
#        "//:PeripheralInterface",
#    ],
#)
#
#mock(
#    name = "MockMutex",
#    srcs = ["@EmbeddedUtilities//:Util/Mutex.h"],
#    deps = ["@EmbeddedUtilities//:MutexHdrsOnly"],
#)
